services:
  koter-tutorials:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - uploads:/app/uploads
    environment:
      - NODE_ENV=production
    networks:
      - easypanel

volumes:
  uploads:

networks:
  easypanel:
    external: true
